name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub Actions"

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14" # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d dist
